import Footer from "./components/Footer/Footer";
import Header from "./components/Header/Header";

import "./globals.scss";
import "./main-page.scss";

export const metadata = {
	title: "ToDo",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<Header/>
				{children}
				<Footer/>
			</body>
		</html>
	);
}
