import "./globals.scss";
import "./main-page.scss";

export const metadata = {
	title: "ToDo",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				{children}
			</body>
		</html>
	);
}
